# Generated by Django 5.0.1 on 2024-02-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_audio_remove_book_category_alter_book_img_and_more'),
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.book'),
        ),
    ]
