# Generated by Django 5.0.1 on 2024-02-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
