# Generated by Django 5.0.1 on 2024-02-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_cart_payable_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payable',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
